import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import './globals.css';
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import localFont from "next/font/local";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
})

const popins = localFont({
  src: '../public/fonts/Poppins-Regular.woff2',
  variable: '--font-popins',
})

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter" >
      <body
        className={popins.className}
      >
        <AuthProvider>
          <NavBar />
          <main className="p-5">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
